source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Stack_Example', :exclusive => true do
  pod "Stack", :path => "../"
end

target 'Stack_Tests', :exclusive => true do
  pod "Stack", :path => "../"

  
end
