source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Stack', :exclusive => true do
  pod "Stack", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Stack", :path => "../"

  pod 'Kiwi'
end
